### ISSUE TITLE
Segmentation Fault (core dump)

### ISSUE THREAD

**Issue by hwcopeland** [ccsb-scripps/AutoDock4#2]
Didn't know where to go to next so I figured its time to just open an issue as experts in the use of Autodock4 are few and far between.

For Reference, All files are included in this master repo: 
https://github.com/Khemiatic-Energistics/compute-infrastructure

Enviorment:
Autodock4 is baked into a container running ubuntu 22.04 (compute-infrastructure/docker/autodock4/Dockerfile) and hosts a series of scripts. Each script in Executed with the Kubernetes Operator in an Apache Airflow DAG, in sequenced and batched processing. 

Upon final execution of Autodock4, am greeted with `Segmentation fault (core dumped)`

```
root@5ac021b5772c:/data# /autodock/autodock4 -p /data/batch0/output/docked/ligand_7.dpf -l /data/batch0/output/docked/ligand_7.dlg -d
Segmentation fault (core dumped)
```

Image is available with `docker pull hwcopeland/auto-docker:latest`

attached are dpf and the log

[ligand_7.dpf.txt](https://github.com/user-attachments/files/17469001/ligand_7.dpf.txt)
[ligand_7.dlg.txt](https://github.com/user-attachments/files/17469002/ligand_7.dlg.txt)

**Comment by diogomart** [comment]
Hello,
We aren't maintaining autodock4 anymore. The AD4 scoring function is supported in both AutoDock-GPU and AutoDock-Vina (with --scoring ad4) in this organizational account, and the search algorithms are far superior. You could try vina as you'd just need to download an executable, it's far easier to use than autodock4, and might be installable from conda-forge for your system.

**Comment by hwcopeland** [comment]
Thanks for the quick response. Does Vina support .dpf? I would prefer to drop in replace binaries without a major overhaul to the scripts.

**Comment by diogomart** [comment]
It does not, but I suspect the amount of work is minimal, and you'll be better off.

You'll need to pass as command line arguments, or in a single config text file (or any combination of the two):
 - ligand filename
 - option `--scoring_ad4`
 - filename prefix for autogrid written maps with `--maps`

**Comment by diogomart** [comment]
https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#a-using-autodock4-forcefield

**Comment by hwcopeland** [comment]
Thank you. Will complete as advised. Closing issue as resolved.
